package db

import (
	"database/sql"
	"fmt"
	"net/url"
	"os"
	"sync"
	"testing"
	"time"

	"levelog/backend/migrations"
)

// Set TEST_DATABASE_URL to run these against a scratch Postgres database
// (see backend/internal/handler/router_integration_test.go for the same
// convention). Skipped entirely otherwise, so `go test ./...` is unaffected.

func withScratchDatabase(t *testing.T) string {
	t.Helper()
	baseDSN := os.Getenv("TEST_DATABASE_URL")
	if baseDSN == "" {
		t.Skip("TEST_DATABASE_URL not set; skipping")
	}

	admin, err := sql.Open("pgx", baseDSN)
	if err != nil {
		t.Fatalf("open admin connection: %v", err)
	}
	t.Cleanup(func() { admin.Close() })

	// Postgres identifiers can't be parameterized; safe here because
	// dbName is entirely generated by this test, never from external
	// input.
	dbName := fmt.Sprintf("levelog_migrate_test_%d", time.Now().UnixNano())
	if _, err := admin.Exec(`CREATE DATABASE ` + dbName); err != nil {
		t.Fatalf("create scratch database %s: %v", dbName, err)
	}
	t.Cleanup(func() {
		// New connection for the DROP: the pool that ran migrations
		// against dbName may still hold connections to it, and Postgres
		// refuses to drop a database with active connections.
		cleanup, err := sql.Open("pgx", baseDSN)
		if err != nil {
			t.Logf("cleanup: open admin connection: %v", err)
			return
		}
		defer cleanup.Close()
		if _, err := cleanup.Exec(`DROP DATABASE IF EXISTS ` + dbName + ` WITH (FORCE)`); err != nil {
			t.Logf("cleanup: drop scratch database %s: %v", dbName, err)
		}
	})

	u, err := url.Parse(baseDSN)
	if err != nil {
		t.Fatalf("parse TEST_DATABASE_URL: %v", err)
	}
	u.Path = "/" + dbName
	return u.String()
}

func countMigrationFiles(t *testing.T) int {
	t.Helper()
	entries, err := migrations.FS.ReadDir(".")
	if err != nil {
		t.Fatalf("read migrations dir: %v", err)
	}
	n := 0
	for _, e := range entries {
		if !e.IsDir() {
			n++
		}
	}
	return n
}

// TestMigrate_ConcurrentInstancesDoNotRace simulates a rolling deploy where
// several app instances start at once against a freshly provisioned,
// not-yet-migrated database (see docs/production-roadmap.md phase 1's
// "複数アプリサーバで動かない要因" #1 and phase 13). Without serialization,
// two instances can both see a migration as not-yet-applied and both try to
// INSERT its filename into schema_migrations, and the second hits a
// primary-key violation — an entirely real failure mode (see filename PK in
// Migrate), not a hypothetical one.
func TestMigrate_ConcurrentInstancesDoNotRace(t *testing.T) {
	dsn := withScratchDatabase(t)

	const instances = 8
	var wg sync.WaitGroup
	errs := make([]error, instances)
	for i := range instances {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			conn, err := Open(dsn, PoolOptions{MaxOpenConns: 3, MaxIdleConns: 1, ConnMaxLifetime: time.Minute})
			if err != nil {
				errs[i] = fmt.Errorf("open: %w", err)
				return
			}
			defer conn.Close()
			errs[i] = Migrate(conn)
		}(i)
	}
	wg.Wait()

	for i, err := range errs {
		if err != nil {
			t.Errorf("instance %d: Migrate returned error: %v", i, err)
		}
	}

	verify, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatalf("open verify connection: %v", err)
	}
	defer verify.Close()

	var count int
	if err := verify.QueryRow(`SELECT COUNT(*) FROM schema_migrations`).Scan(&count); err != nil {
		t.Fatalf("count schema_migrations: %v", err)
	}
	if want := countMigrationFiles(t); count != want {
		t.Errorf("schema_migrations has %d rows, want %d (each migration recorded exactly once)", count, want)
	}
}

// TestMigrate_SecondRunIsNoOp exercises the ordinary (non-racing) restart
// path: re-running Migrate against an already-migrated database must not
// error and must not change the recorded row count.
func TestMigrate_SecondRunIsNoOp(t *testing.T) {
	dsn := withScratchDatabase(t)

	conn, err := Open(dsn, PoolOptions{MaxOpenConns: 5, MaxIdleConns: 2, ConnMaxLifetime: time.Minute})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer conn.Close()

	if err := Migrate(conn); err != nil {
		t.Fatalf("first Migrate: %v", err)
	}
	if err := Migrate(conn); err != nil {
		t.Fatalf("second Migrate: %v", err)
	}

	var count int
	if err := conn.QueryRow(`SELECT COUNT(*) FROM schema_migrations`).Scan(&count); err != nil {
		t.Fatalf("count schema_migrations: %v", err)
	}
	if want := countMigrationFiles(t); count != want {
		t.Errorf("schema_migrations has %d rows after two runs, want %d", count, want)
	}
}
